name: Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  teste-ui:
    name: Teste de UI (Cypress)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        working-directory: Teste-de-UI
        run: npm install

      - name: Executar testes do Cypress
        working-directory: Teste-de-UI
        run: npm test || true

      - name: Armazenar screenshots e vídeos
        uses: actions/upload-artifact@v4
        with:
          name: resultados-teste-ui
          path: Teste-de-UI/cypress/screenshots

  teste-api:
    name: Testes de API (Jest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        working-directory: Testes-de-API
        run: npm install

      - name: Executar testes de API
        working-directory: Testes-de-API
        run: npm test || true

      - name: Armazenar logs dos testes
        uses: actions/upload-artifact@v4
        with:
          name: resultados-teste-api
          path: Testes-de-API/test-results

  teste-performance:
    name: Testes de Performance (k6)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Adicionar repositório do k6 e instalar
        run: |
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Executar testes de performance
        working-directory: Testes-de-Performance
        run: k6 run load_test.js || true

      - name: Armazenar logs dos testes de performance
        uses: actions/upload-artifact@v4
        with:
          name: resultados-teste-performance
          path: Testes-de-Performance/*.json
